// Package report renders a single proofload run into a self-contained, offline
// HTML document. Everything needed to view the report — styles and charts — is
// embedded in the file: charts are inline SVG generated in pure Go, so there is
// no external JavaScript, CSS, font, or network dependency of any kind.
//
// The report is read from a run directory using the emit package's readers
// (manifest, summary, optional verification report, and the Parquet time-series).
package report

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/proofload/proofload/core/domain"
	"github.com/proofload/proofload/core/emit"
)

// pathsFor reconstructs the canonical emit.Paths for a run directory of the form
// <base>/results/<target>/<runID>, reusing emit.Layout so artifact basenames are
// never duplicated here.
func pathsFor(runDir string) emit.Paths {
	clean := filepath.Clean(runDir)
	id := domain.RunID(filepath.Base(clean))
	target := filepath.Base(filepath.Dir(clean))
	base := filepath.Dir(filepath.Dir(filepath.Dir(clean)))
	return emit.Layout(base, target, id)
}

// Render reads the artifacts in runDir and returns a complete, standalone HTML5
// document for the run. manifest.json and summary.json are required; the Parquet
// time-series and verify.json are optional (their sections are omitted if absent
// or unreadable).
func Render(runDir string) ([]byte, error) {
	p := pathsFor(runDir)
	m, err := emit.ReadManifest(p)
	if err != nil {
		return nil, err
	}
	r, err := emit.ReadSummary(p)
	if err != nil {
		return nil, err
	}

	var body strings.Builder
	body.WriteString(headerHTML(m))
	if r.ClientBound {
		body.WriteString(`<div class="banner warn">Client-bound: the load client, not the target, ` +
			`was the bottleneck for this run. Throughput and latency numbers do not reflect the target.</div>`)
	}
	body.WriteString(summaryHTML(r))
	if len(r.ByOp) > 0 {
		body.WriteString(byOpHTML(r))
	}
	if snaps, err := emit.ReadTimeseriesParquet(p); err == nil {
		body.WriteString(timeseriesHTML(snaps))
	}
	if v, err := readVerifyIfPresent(p); err == nil && v != nil {
		body.WriteString(correctnessHTML(*v))
	}
	body.WriteString(metadataHTML(m))

	return []byte(document(m, body.String())), nil
}

// WriteReport renders the run in runDir and writes it to report.html inside that
// directory, returning the path written.
func WriteReport(runDir string) (string, error) {
	html, err := Render(runDir)
	if err != nil {
		return "", err
	}
	out := filepath.Join(runDir, "report.html")
	if err := os.WriteFile(out, html, 0o644); err != nil {
		return "", err
	}
	return out, nil
}

// readVerifyIfPresent returns the verification report, or (nil, nil) if the file
// does not exist.
func readVerifyIfPresent(p emit.Paths) (*domain.VerifyReport, error) {
	if _, err := os.Stat(p.VerifyJSON); err != nil {
		return nil, nil
	}
	v, err := emit.ReadVerify(p)
	if err != nil {
		return nil, err
	}
	return &v, nil
}

// document wraps rendered body HTML in a valid, standalone HTML5 shell.
func document(m domain.Manifest, body string) string {
	title := esc(m.Target + " — proofload run " + string(m.RunID))
	return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">` +
		`<meta name="viewport" content="width=device-width, initial-scale=1">` +
		`<title>` + title + `</title>` + styleBlock + `</head><body><main class="wrap">` +
		body +
		`<footer>Generated by proofload &middot; self-contained offline report.</footer>` +
		`</main></body></html>`
}
